In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix,f1_score



In [8]:
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
uploaded = files.upload()

# Load the dataset
#dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/bank-data/bank-full.csv')
import io
df = pd.read_csv(io.BytesIO(uploaded['/content/drive/MyDrive/Colab Notebooks/Datasets/bank-data/bank-full.csv']))



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Saving bank-full.csv to bank-full.csv


KeyError: '/content/drive/MyDrive/Colab Notebooks/Datasets/bank-data/bank-full.csv'

age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0      58;"management";"married";"tertiary";"no";2143...                                                                                                  
1      44;"technician";"single";"secondary";"no";29;"...                                                                                                  
2      33;"entrepreneur";"married";"secondary";"no";2...                                                                                                  
3      47;"blue-collar";"married";"unknown";"no";1506...                                                                                                  
4      33;"unknown";"single";"unknown";"no";1;"no";"n...                                                                                                  
...                                                  ...                                                                                                  
45206  51;"technician";"married";"tertiary";"no";825;...                                                                                                  
45207  71;"retired";"divorced";"primary";"no";1729;"n...                                                                                                  
45208  72;"retired";"married";"secondary";"no";5715;"...                                                                                                  
45209  57;"blue-collar";"married";"secondary";"no";66...                                                                                                  
45210  37;"entrepreneur";"married";"secondary";"no";2...                                                                                                  

[45211 rows x 1 columns]

In [ ]:
#Step 1: Define a Threshold and Convert to Binary Labels
threshold = 10  # Adjust the threshold based on your data
binary_labels = np.where(dataset['As'] > threshold, 1, 0)
dataset['As_binary'] = binary_labels


In [ ]:
dataset

Sample ID#  Latitude  Longitude    pH    EC  TDS    HCO3   PO4    Cl2  \
0            1    24.606     88.249  6.90  2000  770  400.32  1.22  12.34   
1            2    24.601     88.250  7.46   885  250  450.36  0.71  11.09   
2            3    24.604     88.242  7.95   890  210  350.28  1.08  14.11   
3            4    24.601     88.248  7.02   828  250  500.40  0.92  13.94   
4            5    24.601     88.249  7.35   905  240  350.28  0.52  12.74   
5            6    24.602     88.252  7.05  1043  320  500.40  0.86  13.29   
6            7    24.598     88.256  7.44   642  200  350.28  0.74  14.04   
7            8    24.607     88.245  7.49   366  120  250.20  0.41  14.93   
8            9    24.612     88.257  6.98  1270  380  550.44  1.80  14.73   
9           10    24.610     88.246  6.99  1015  250  450.36  0.55  13.98   
10          11    24.577     88.290  7.18   632  190  400.32  0.62  13.79   
11          12    24.578     88.269  6.95   995  300  450.36  0.42  14.98   
12          13    24.614     88.231  7.15  1115  300  450.36  0.49  15.21   
13          14    24.614     88.238  7.65  2000  730  300.24  0.88  15.78   
14          15    24.608     88.233  7.16  1120  340  450.36  0.73  15.21   
15          16    24.613     88.225  7.27   775  230  450.36  0.46  14.98   
16          17    24.613     88.229  7.12  1130  330  550.44  0.69  15.95   
17          18    24.615     88.228  7.81   813  250  400.32  0.22  16.28   
18          19    24.582     88.285  7.63   995  270  450.36  0.14  16.26   
19          20    24.576     88.265  7.58  1226  330  300.24  0.32  15.32   
20          21    24.620     88.260  7.64   964  290  400.32  0.32  14.29   
21          22    24.629     88.261  7.36   773  230  350.28  0.39  15.37   
22          23    24.380     88.160  8.09   432  140  400.32  0.47  14.79   
23          24    24.393     88.170  7.84   549  170  300.24  0.51  13.78   
24          25    24.340     88.174  7.92   560  160  300.24  0.68  12.98   
25          26    24.365     88.154  7.94   806  240  500.40  0.56  11.90   
26          27    24.364     88.155  7.70   765  220  450.36  0.72  12.89   
27          28    24.365     88.171  7.99   556  150  250.20  0.78  12.36   
28          29    24.373     88.174  8.16   512  160  300.24  1.39  11.90   
29          30    24.379     88.179  8.05   536  150  200.16  0.27  10.92   

     SO4   NO3  As    Fe    Mn     Na     K      Ca      Mg  As_binary  
0   1.13  0.10  25  0.38  0.38  68.23  3.13  195.59  151.69          1  
1   0.12  0.07  20  0.29  0.79  40.14  2.00   83.37   51.54          1  
2   0.07  0.04  50  0.44  0.74  32.79  2.87   41.68   51.54          1  
3   0.11  0.06  10  0.52  0.52  22.38  1.91   80.16   35.98          0  
4   0.76  0.61  23  0.01  0.01  33.22  2.15  101.00   33.06          1  
5   0.18  0.13  27  0.24  0.80  40.00  2.21  128.26   24.31          1  
6   0.22  0.94  18  0.43  0.43  31.53  1.66  107.41   23.34          1  
7   0.65  0.57  26  0.34  0.34  37.50  1.82   67.33   11.67          1  
8   0.34  0.27  40  0.32  0.32  35.56  1.25  166.73   37.92          1  
9   0.72  0.60  27  0.11  0.81  37.10  1.28   81.76   34.03          1  
10  0.92  0.78  11  0.31  0.91  40.43  1.54   99.39   34.03          1  
11  0.16  0.05  22  0.47  0.57  39.20  1.64  139.48   35.98          1  
12  0.29  0.23  10  0.14  0.14  48.24  1.51   67.33   63.21          0  
13  0.56  0.48  77  0.65  0.65  41.18  1.50   92.99   55.43          1  
14  0.19  0.12  60  0.59  0.79  44.54  1.54   96.19   59.32          1  
15  0.81  0.74  50  0.44  0.44  37.80  0.74  121.84   24.31          1  
16  0.17  0.11  46  0.68  0.68  39.41  1.76  139.48   35.01          1  
17  0.16  0.04  56  0.59  0.79  30.45  1.32  113.83   26.25          1  
18  0.04  0.02  70  0.11  0.11  37.18  1.69  120.24   24.31          1  
19  0.26  0.14  36  0.21  0.21  33.09  0.81   89.78   35.98          1  
20  0.12  0.08  31  0.45  0.45  27.71  1.12  113.83   34.03          1  
21  0.13  

In [ ]:
target = "As_binary"

# Extract features and target variable
x = dataset.drop(["As_binary","Sample ID#" , "Latitude" , "Longitude" , "As"],axis = 1)
y = dataset[target]


# **Statistics info**

In [ ]:

# Print statistics for the independent features
for column in x.columns:
    print(f"\nStatistics for {column}:")
    print(f"Mean: {x[column].mean()}")
    print(f"Mode: {x[column].mode().values[0]}")  # Mode can have multiple values, so taking the first one
    print(f"Median: {x[column].median()}")
    print(f"Standard Deviation: {x[column].std()}")
    print(f"Skewness: {x[column].skew()}")



Statistics for   pH:
Mean: 7.494
Mode: 6.9
Median: 7.475
Standard Deviation: 0.39066344983179935
Skewness: 0.0911868102032183

Statistics for EC:
Mean: 903.2666666666667
Mode: 995
Median: 856.5
Standard Deviation: 381.5062645423499
Skewness: 1.4742412484654708

Statistics for TDS:
Mean: 272.3333333333333
Mode: 250
Median: 245.0
Standard Deviation: 145.83134645608743
Skewness: 2.456548655286224

Statistics for HCO3:
Mean: 393.648
Mode: 450.36
Median: 400.32
Standard Deviation: 90.79128890311921
Skewness: -0.2334597689281686

Statistics for PO4:
Mean: 0.6623333333333332
Mode: 0.32
Median: 0.5900000000000001
Standard Deviation: 0.3582782903461126
Skewness: 1.359468043775099

Statistics for Cl2:
Mean: 14.004333333333333
Mode: 11.9
Median: 14.075
Standard Deviation: 1.491871500737461
Skewness: -0.428990973639237

Statistics for SO4:
Mean: 0.37399999999999994
Mode: 0.12
Median: 0.20500000000000002
Standard Deviation: 0.30503363296754565
Skewness: 0.8893549761575533

Statistics for NO3:
Mean

In [ ]:
# #step 2: Split the Dataset
# xtrain,xtest,ytrain,ytest=train_test_split(dataset.drop(["As_binary","Sample ID#" , "Latitude" , "Longitude" , "As"],axis=1),binary_labels,test_size=0.4,random_state=0)
# print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape)


In [ ]:
# Standard scaling
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
x_scaled


array([[-1.54648351,  2.92388978,  3.4709575 ,  0.07474351,  1.58312724,
        -1.13467248,  2.52078437, -0.68836612,  0.10136737, -0.41949252,
         4.08651755,  2.96877292,  2.89694921,  4.29429704],
       [-0.08851926, -0.04869891, -0.155763  ,  0.63531983,  0.13531811,
        -1.98686992, -0.8469302 , -0.79821178, -0.34730788,  1.15841511,
         0.36040732,  0.73972747, -0.4182446 ,  0.69524227],
       [ 1.18719946, -0.03536892, -0.4347415 , -0.48583281,  1.18568944,
         0.07203909, -1.01364874, -0.90805743,  0.4004842 ,  0.96598735,
        -0.61456279,  2.4558952 , -1.64984707,  0.69524227],
       [-1.2340626 , -0.20066085, -0.155763  ,  1.19589615,  0.73147481,
        -0.04385976, -0.88027391, -0.834827  ,  0.79930665,  0.11930521,
        -1.99543881,  0.56219288, -0.51307415,  0.13606811],
       [-0.37490509,  0.00462106, -0.22550762, -0.48583281, -0.40406176,
        -0.8619693 ,  1.28706715,  1.17901006, -1.74318643, -1.84345794,
        -0.55752372,  1.03

# Logistic Regression

In [ ]:
 #Step 5: Train Logistic Regression Model
model1 = LogisticRegression()
model1.fit(x_scaled, y)
pred=model1.predict(x_scaled)

# Make predictions
logistic_predictions = model1.predict(x_scaled)


 #Evaluate Logistic Regression Model
logistic_accuracy = accuracy_score(y, logistic_predictions)
logistic_precision = precision_score(y, logistic_predictions)
logistic_recall = recall_score(y, logistic_predictions)
logistic_conf_matrix = confusion_matrix(y, logistic_predictions)

print("Logistic Regression Metrics:")
print(f"Accuracy: {logistic_accuracy}")
print(f"Precision: {logistic_precision}")
print(f"Recall: {logistic_recall}")
print(f"Confusion Matrix:\n{logistic_conf_matrix}")


Logistic Regression Metrics:
Accuracy: 0.9333333333333333
Precision: 0.9310344827586207
Recall: 1.0
Confusion Matrix:
[[ 1  2]
 [ 0 27]]


# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Train Decision Tree Model on the full dataset
tree_model = DecisionTreeClassifier()
tree_model.fit(x_scaled, y)

# Make predictions on the full dataset
tree_predictions_full = tree_model.predict(x_scaled)

# Evaluate the model on the full dataset
tree_accuracy_full = accuracy_score(y, tree_predictions_full)
tree_precision_full = precision_score(y, tree_predictions_full)
tree_recall_full = recall_score(y, tree_predictions_full)
tree_conf_matrix_full = confusion_matrix(y, tree_predictions_full)
print("Decision Tree Metrics on Full Dataset:")
print(f"Accuracy: {tree_accuracy_full}")
print(f"Precision: {tree_precision_full}")
print(f"Recall: {tree_recall_full}")
print(f"Confusion Matrix:\n{tree_conf_matrix_full}")



Decision Tree Metrics on Full Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
[[ 3  0]
 [ 0 27]]


# KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Train KNeighborsClassifier on the full dataset
knn_model = KNeighborsClassifier()
knn_model.fit(x_scaled, y)

# Make predictions on the full dataset
knn_predictions_full = knn_model.predict(x_scaled)

# Evaluate the model on the full dataset
knn_accuracy_full = accuracy_score(y, knn_predictions_full)
knn_precision_full = precision_score(y, knn_predictions_full)
knn_recall_full = recall_score(y, knn_predictions_full)
knn_conf_matrix_full = confusion_matrix(y, knn_predictions_full)
print("KNeighborsClassifier Metrics on Full Dataset:")
print(f"Accuracy: {knn_accuracy_full}")
print(f"Precision: {knn_precision_full}")
print(f"Recall: {knn_recall_full}")
print(f"Confusion Matrix:\n{knn_conf_matrix_full}")



KNeighborsClassifier Metrics on Full Dataset:
Accuracy: 0.9
Precision: 0.9
Recall: 1.0
Confusion Matrix:
[[ 0  3]
 [ 0 27]]


# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Train Random Forest Model on the full dataset
rf_model = RandomForestClassifier()
rf_model.fit(x_scaled, y)

# Make predictions on the full dataset
rf_predictions_full = rf_model.predict(x_scaled)

# Evaluate the model on the full dataset
rf_accuracy_full = accuracy_score(y, rf_predictions_full)
rf_precision_full = precision_score(y, rf_predictions_full)
rf_recall_full = recall_score(y, rf_predictions_full)
rf_conf_matrix_full = confusion_matrix(y, rf_predictions_full)
print("Random Forest Metrics on Full Dataset:")
print(f"Accuracy: {rf_accuracy_full}")
print(f"Precision: {rf_precision_full}")
print(f"Recall: {rf_recall_full}")
print(f"Confusion Matrix:\n{rf_conf_matrix_full}")


Random Forest Metrics on Full Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
[[ 3  0]
 [ 0 27]]


# Support Vector Machine

In [ ]:
from sklearn.svm import SVC

# Train SVM Model on the full dataset
svm_model = SVC()
svm_model.fit(x_scaled, y)

# Make predictions on the full dataset
svm_predictions_full = svm_model.predict(x_scaled)

# Evaluate the model on the full dataset
svm_accuracy_full = accuracy_score(y, svm_predictions_full)
svm_precision_full = precision_score(y, svm_predictions_full)
svm_recall_full = recall_score(y, svm_predictions_full)
svm_conf_matrix_full = confusion_matrix(y, svm_predictions_full)

print("Support Vector Machine Metrics on Full Dataset:")
print(f"Accuracy: {svm_accuracy_full}")
print(f"Precision: {svm_precision_full}")
print(f"Recall: {svm_recall_full}")
print(f"Confusion Matrix:\n{svm_conf_matrix_full}")


Support Vector Machine Metrics on Full Dataset:
Accuracy: 0.9
Precision: 0.9
Recall: 1.0
Confusion Matrix:
[[ 0  3]
 [ 0 27]]


# GaussianNB


In [ ]:
from sklearn.naive_bayes import GaussianNB

# Train Gaussian Naive Bayes Model on the full dataset
nb_model = GaussianNB()
nb_model.fit(x_scaled, y)

# Make predictions on the full dataset
nb_predictions_full = nb_model.predict(x_scaled)

# Evaluate the model on the full dataset
nb_accuracy_full = accuracy_score(y, nb_predictions_full)
nb_precision_full = precision_score(y, nb_predictions_full)
nb_recall_full = recall_score(y, nb_predictions_full)
nb_conf_matrix_full = confusion_matrix(y, nb_predictions_full)


print("Gaussian Naive Bayes Metrics on Full Dataset:")
print(f"Accuracy: {nb_accuracy_full}")
print(f"Precision: {nb_precision_full}")
print(f"Recall: {nb_recall_full}")
print(f"Confusion Matrix:\n{nb_conf_matrix_full}")


Gaussian Naive Bayes Metrics on Full Dataset:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
Confusion Matrix:
[[ 3  0]
 [ 0 27]]


# Code For Map

In [ ]:

# Combine actual and predicted values into a dataset
map_df = pd.DataFrame({
    'mLatitude': dataset["Latitude"].iloc[:len(x_scaled)],
    'mLongitude': dataset["Longitude"].iloc[:len(x_scaled)],
    'Actual_As': y,
    'Predicted_As': logistic_predictions
})

# Create a base map centered at the mean of the coordinates
map_center = [map_df["mLatitude"].mean(), map_df["mLongitude"].mean()]
mymap = folium.Map(location=map_center, zoom_start=10)

# Create a MarkerCluster to group markers if you have many data points
marker_cluster = MarkerCluster().add_to(mymap)

# Add markers for each data point with actual and predicted values
for index, row in map_df.iterrows():
    actual_color = 'green' if row['Actual_As'] == 1 else 'blue'
    predicted_color = 'red' if row['Predicted_As'] == 1 else 'yellow'

    popup_text = f"Actual: {row['Actual_As']}, Predicted: {row['Predicted_As']}"

    if row['Actual_As'] == 1 and row['Predicted_As'] == 1:
        popup_text += ' - True Positive'
    elif row['Actual_As'] == 0 and row['Predicted_As'] == 0:
        popup_text += ' - True Negative'
    elif row['Actual_As'] == 0 and row['Predicted_As'] == 1:
        popup_text += ' - False Positive'
    elif row['Actual_As'] == 1 and row['Predicted_As'] == 0:
        popup_text += ' - False Negative'

    folium.CircleMarker(
        location=[row["mLatitude"], row["mLongitude"]],
        radius=10,
        popup=popup_text,
        fill=True,
        color=actual_color,
        fill_color=actual_color,
        fill_opacity=0.7,
    ).add_to(marker_cluster)

    folium.CircleMarker(
        location=[row["mLatitude"] + 0.02, row["mLongitude"]],
        radius=8,
        popup=popup_text,
        fill=True,
        color=predicted_color,
        fill_color=predicted_color,
        fill_opacity=0.7,
    ).add_to(marker_cluster)

# Save the map to your Google Drive
output_path = '/content/drive/MyDrive/Colab Notebooks/Arsenic Prediction/classification_comparison_map.html'
mymap.save(output_path)

In [ ]:
import folium
from folium.plugins import MarkerCluster
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix,f1_score
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Arsenic Prediction/water quality.csv')
#Step 1: Define a Threshold and Convert to Binary Labels
threshold = 10  # Adjust the threshold based on your data
binary_labels = np.where(dataset['As'] > threshold, 1, 0)
dataset['As_binary'] = binary_labels
#step 2: Split the Dataset
xtrain,xtest,ytrain,ytest=train_test_split(dataset.drop(["As_binary","Sample ID#" , "Latitude" , "Longitude" , "As"],axis=1),binary_labels,test_size=0.4,random_state=0)
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape)
# Step 3:standard scaling
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

 #Step 5: Train Logistic Regression Model
model1 = LogisticRegression()
model1.fit(xtrain, ytrain)
pred=model1.predict(xtest)

# Make predictions
logistic_predictions = model1.predict(xtest)
 #Evaluate Logistic Regression Model
logistic_accuracy = accuracy_score(ytest, logistic_predictions)
logistic_precision = precision_score(ytest, logistic_predictions)
logistic_recall = recall_score(ytest, logistic_predictions)
logistic_conf_matrix = confusion_matrix(ytest, logistic_predictions)
print("Logistic Regression Metrics:")
print(f"Accuracy: {logistic_accuracy}")
print(f"Precision: {logistic_precision}")
print(f"Recall: {logistic_recall}")
print(f"Confusion Matrix:\n{logistic_conf_matrix}")



# Combine actual and predicted values into a dataset
# Combine actual and predicted values into a dataset
map_df = pd.DataFrame({
    'mLatitude': dataset["Latitude"].iloc[:len(ytest)],  # Use len(ytest) instead of len(xtest)
    'mLongitude': dataset["Longitude"].iloc[:len(ytest)],  # Use len(ytest) instead of len(xtest)
    'Actual_As': ytest,
    'Predicted_As': logistic_predictions
})

# Create a base map centered at the mean of the coordinates
map_center = [map_df["mLatitude"].mean(), map_df["mLongitude"].mean()]
mymap = folium.Map(location=map_center, zoom_start=10)

# Create a MarkerCluster to group markers if you have many data points
marker_cluster = MarkerCluster().add_to(mymap)

# Add markers for each data point with actual and predicted values
for index, row in map_df.iterrows():
    actual_color = 'green' if row['Actual_As'] == 1 else 'blue'
    predicted_color = 'red' if row['Predicted_As'] == 1 else 'yellow'

    popup_text = f"Actual: {row['Actual_As']}, Predicted: {row['Predicted_As']}"

    if row['Actual_As'] == 1 and row['Predicted_As'] == 1:
        popup_text += ' - True Positive'
    elif row['Actual_As'] == 0 and row['Predicted_As'] == 0:
        popup_text += ' - True Negative'
    elif row['Actual_As'] == 0 and row['Predicted_As'] == 1:
        popup_text += ' - False Positive'
    elif row['Actual_As'] == 1 and row['Predicted_As'] == 0:
        popup_text += ' - False Negative'

    folium.CircleMarker(
        location=[row["mLatitude"], row["mLongitude"]],
        radius=10,
        popup=popup_text,
        fill=True,
        color=actual_color,
        fill_color=actual_color,
        fill_opacity=0.7,
    ).add_to(marker_cluster)

    folium.CircleMarker(
        location=[row["mLatitude"] + 0.02, row["mLongitude"]],
        radius=8,
        popup=popup_text,
        fill=True,
        color=predicted_color,
        fill_color=predicted_color,
        fill_opacity=0.7,
    ).add_to(marker_cluster)

# Save the map to your Google Drive
output_path = '/content/drive/MyDrive/Colab Notebooks/Arsenic Prediction/classification_comparison_map.html'
mymap.save(output_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(18, 14) (12, 14) (18,) (12,)
Logistic Regression Metrics:
Accuracy: 0.9166666666666666
Precision: 1.0
Recall: 0.9166666666666666
Confusion Matrix:
[[ 0  0]
 [ 1 11]]


In [ ]:
import folium
from folium.plugins import MarkerCluster
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

from google.colab import drive
drive.mount('/content/drive')

# Load the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Arsenic Prediction/water quality.csv')

#Step 1: Define a Threshold and Convert to Binary Labels
threshold = 10  # Adjust the threshold based on your data
binary_labels = np.where(dataset['As'] > threshold, 1, 0)
dataset['As_binary'] = binary_labels

# Define features and target variable
#features =  # Replace with your actual feature names
target = "As_binary"

# Extract features and target variable
x = dataset.drop(["As_binary","Sample ID#" , "Latitude" , "Longitude" , "As"],axis = 1)
y = dataset[target]

# Standard scaling
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# Train Logistic Regression Model on the full dataset
model = LogisticRegression()
model.fit(x_scaled, y)

# Make predictions on the full dataset
logistic_predictions_full = model.predict(x_scaled)

# Evaluate the model on the full dataset
logistic_accuracy_full = accuracy_score(y, logistic_predictions_full)
logistic_precision_full = precision_score(y, logistic_predictions_full)
logistic_recall_full = recall_score(y, logistic_predictions_full)
logistic_conf_matrix_full = confusion_matrix(y, logistic_predictions_full)
print("Logistic Regression Metrics on Full Dataset:")
print(f"Accuracy: {logistic_accuracy_full}")
print(f"Precision: {logistic_precision_full}")
print(f"Recall: {logistic_recall_full}")
print(f"Confusion Matrix:\n{logistic_conf_matrix_full}")

# Combine actual and predicted values into a dataset
map_df = pd.DataFrame({
    'mLatitude': dataset["Latitude"],
    'mLongitude': dataset["Longitude"],
    'Actual_As': y,
    'Predicted_As': logistic_predictions_full
})

# Create a base map centered at the mean of the coordinates
map_center = [map_df["mLatitude"].mean(), map_df["mLongitude"].mean()]
mymap = folium.Map(location=map_center, zoom_start=10)

# Create a MarkerCluster to group markers if you have many data points
marker_cluster = MarkerCluster().add_to(mymap)

# Add markers for each data point with actual and predicted values
for index, row in map_df.iterrows():
    actual_color = 'green' if row['Actual_As'] == 1 else 'blue'
    predicted_color = 'red' if row['Predicted_As'] == 1 else 'yellow'

    popup_text = f"Actual: {row['Actual_As']}, Predicted: {row['Predicted_As']}"

    if row['Actual_As'] == 1 and row['Predicted_As'] == 1:
        popup_text += ' - True Positive'
    elif row['Actual_As'] == 0 and row['Predicted_As'] == 0:
        popup_text += ' - True Negative'
    elif row['Actual_As'] == 0 and row['Predicted_As'] == 1:
        popup_text += ' - False Positive'
    elif row['Actual_As'] == 1 and row['Predicted_As'] == 0:
        popup_text += ' - False Negative'

    folium.CircleMarker(
        location=[row["mLatitude"], row["mLongitude"]],
        radius=10,
        popup=popup_text,
        fill=True,
        color=actual_color,
        fill_color=actual_color,
        fill_opacity=0.7,
    ).add_to(marker_cluster)

    folium.CircleMarker(
        location=[row["mLatitude"] + 0.02, row["mLongitude"]],
        radius=8,
        popup=popup_text,
        fill=True,
        color=predicted_color,
        fill_color=predicted_color,
        fill_opacity=0.7,
    ).add_to(marker_cluster)

# Save the map to your Google Drive
output_path = '/content/drive/MyDrive/Colab Notebooks/Arsenic Prediction/classification_comparison_map_full.html'
mymap.save(output_path)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Logistic Regression Metrics on Full Dataset:
Accuracy: 0.9333333333333333
Precision: 0.9310344827586207
Recall: 1.0
Confusion Matrix:
[[ 1  2]
 [ 0 27]]
